sudo: required 

language: python

before_install:
  - sudo apt-get update -y

install:
  - git clone https://github.com/sstephenson/bats.git && bats/install.sh .
  - git clone https://github.com/clustervision/trinity && trinity/update master

script:
  - ./bin/bats master/t1.1.bats
  - ls -a

