#!/bin/bash

source /root/keystonerc_admin
keystone tenant-create --name $1
obol -H ldap://controller -w system user add $1 --password system --cn $1 --sn $1 --givenName $1
keystone user-role-add --user=$1 --tenant=$1 --role=admin

cat > /root/keystonerc_$1 <<EOF
export OS_USERNAME=$1
export OS_TENANT_NAME=$1
export OS_PASSWORD=system
export OS_AUTH_URL=http://10.141.255.254:5000/v2.0/
export OS_REGION_NAME=regionOne
export PS1='[\u@\h \W(keystone_$1)]\\$ '
EOF


TOKEN=$(http --ignore-stdin -b POST http://10.141.255.254:32123/trinity/v1/login \
        X-Tenant:admin \
        username=admin \
        password=system \
        | jq --raw-output '.token')

http --ignore-stdin --check-status \
        --timeout=600 \
       PUT http://10.141.255.254:32123/trinity/v1/clusters/$1 \
       X-Tenant:admin \
       X-Auth-Token:$TOKEN \
       specs:='{"default":2}'


