#!/bin/bash

source /root/keystonerc_admin
keystone tenant-create --name a
keystone user-create --name a --tenant a --pass system

cat > /root/keystonerc_a <<EOF
export OS_USERNAME=a
export OS_TENANT_NAME=a
export OS_PASSWORD=system
export OS_AUTH_URL=http://10.141.255.254:5000/v2.0/
export OS_REGION_NAME=regionOne
export PS1='[\u@\h \W(keystone_a)]\\$ '
EOF


TOKEN=$(http --ignore-stdin -b POST http://10.141.255.254:32123/trinity/v1/login \
        X-Tenant:admin \
        username=admin \
        password=system \
        | jq --raw-output '.token')

http --ignore-stdin --check-status \
        --timeout=600 \
       PUT http://10.141.255.254:32123/trinity/v1/clusters/a \
       X-Tenant:admin \
       X-Auth-Token:$TOKEN \
       specs:='{"default":2}'

